"""
Time-Reversed Entropic Cosmology: Hybrid Engine Edition
===================================================================
An informational ontology simulation utilizing a hidden background fabric
of Fabric Quanta to derive spatial coordinates relationally. 

The bit mutation engine and L0 ("01") filter run continuously to generate 
the true background spacetime fabric. 

If --spectrum is provided, the engine operates in HYBRID MODE: the algorithmic
L1-L3 density filters run to show natural emergence (Track A), while the 
imported empirical spectrum data is simultaneously mapped onto the active L0 
fabric to show the real-world historical trajectory (Track B).

Copyright 2026 - Juha Meskanen, The Abstract Universe Project
"""

import random
import argparse
import json
import numpy as np

import matplotlib
try:
    matplotlib.use('TkAgg')
except:
    pass

import matplotlib.pyplot as plt
from numba import njit
from scipy.interpolate import pchip_interpolate, PchipInterpolator

# ===========================================================================
# HYBRID SPECTRUM MAPPER — Maps Empirical Data onto Active Bitfield Fabric
# ===========================================================================

class HybridSpectrumMapper:
    """
    Tracks the active L0 fabric quanta generated by the bitfield mutations
    and maps empirical particle abundances directly onto the running engine.
    """
    T_MIN_YEARS = 1e-4

    def __init__(self, json_path: str, age_limit_years: float):
        with open(json_path, 'r') as f:
            self.data = json.load(f)
        self.t_max_years = age_limit_years
        self._build_interpolators()

    def _time_to_lookup_fraction(self, t_years: float) -> float:
        log_t   = np.log10(max(t_years, self.T_MIN_YEARS))
        log_min = np.log10(self.T_MIN_YEARS)
        log_max = np.log10(self.t_max_years)
        return np.clip((log_t - log_min) / (log_max - log_min), 0.0, 1.0)

    def _build_interpolators(self):
        self.interpolators = {}
        self.earliest_true_fraction = {}
        
        for level_key, level_data in self.data["levels"].items():
            pts = level_data["abundances"]
            raw_years = np.array([p["time_years"] for p in pts], dtype=np.float64)
            raw_steps = np.array([self._time_to_lookup_fraction(y) for y in raw_years], dtype=np.float64)
            raw_densities = np.array([p["density_per_m3"] for p in pts], dtype=np.float64)
            
            if len(raw_steps) > 0:
                self.earliest_true_fraction[level_key] = float(np.min(raw_steps))
            else:
                self.earliest_true_fraction[level_key] = 1.0

            steps = np.concatenate((np.array([0.0]), raw_steps))
            
            if level_key == "L0":
                log_densities = np.log10(raw_densities + 1e-15)
                max_log = np.max(log_densities)
                min_log = np.min(log_densities)
                norm_volume = 1.0 - ((log_densities - min_log) / (max_log - min_log + 1e-15))
                counts = np.concatenate((np.array([0.0]), norm_volume))
            else:
                peak_val = np.max(raw_densities) if np.max(raw_densities) > 0 else 1.0
                norm_matter = raw_densities / peak_val
                counts = np.concatenate((np.array([0.0]), norm_matter))
            
            order = np.argsort(steps)
            unique_steps, unique_indices = np.unique(steps[order], return_index=True)
            self.interpolators[level_key] = PchipInterpolator(unique_steps, counts[order][unique_indices])
            
    def get_empirical_fractions(self, step_fraction: float) -> dict:
        result = {}
        for level_key, spline in self.interpolators.items():
            if level_key != "L0" and step_fraction < self.earliest_true_fraction[level_key]:
                result[level_key] = 0.0
            else:
                result[level_key] = max(0.0, float(spline(step_fraction)))
        return result

# ===========================================================================
# BITSTRING ENGINE (Always Active — Generates Spacetime Fabric)
# ===========================================================================

@njit(fastmath=True)
def compute_entropy(bitstring: np.ndarray) -> float:
    n = bitstring.size
    if n == 0: return 0.0
    count1 = np.sum(bitstring)
    count0 = n - count1
    p0 = count0 / n
    p1 = count1 / n
    entropy = 0.0
    if p0 > 0.0: entropy -= p0 * np.log2(p0)
    if p1 > 0.0: entropy -= p1 * np.log2(p1)
    return entropy


@njit(fastmath=True)
def run_graviton_filter(bitfield: np.ndarray, w: int, target_val: int) -> np.ndarray:
    num_fragments = bitfield.size // w
    success_string = np.zeros(num_fragments, dtype=np.uint8)
    for m in range(num_fragments):
        val = 0
        start_idx = m * w
        for j in range(w):
            if bitfield[start_idx + j]:
                val |= (1 << (w - 1 - j))
        if val == target_val:
            success_string[m] = 1
    return success_string


@njit(fastmath=True)
def run_recursive_density_filter(input_string: np.ndarray, window_size: int, threshold: int) -> np.ndarray:
    if input_string.size < window_size:
        return np.zeros(0, dtype=np.uint8)
    num_fragments = input_string.size // window_size
    success_string = np.zeros(num_fragments, dtype=np.uint8)
    for m in range(num_fragments):
        density = 0
        start_idx = m * window_size
        for j in range(window_size):
            density += input_string[start_idx + j]
        if density >= threshold:
            success_string[m] = 1
    return success_string


class EntropicCosmologyEngine:
    def __init__(self, total_bits, pattern_str, l1_w, l1_t, l2_w, l2_t, l3_w, l3_t):
        self.total_bits = total_bits
        self.w = len(pattern_str)
        self.l1_w, self.l1_t = l1_w, l1_t
        self.l2_w, self.l2_t = l2_w, l2_t
        self.l3_w, self.l3_t = l3_w, l3_t

        self.target_val = 0
        for i, char in enumerate(pattern_str):
            if char == '1':
                self.target_val |= (1 << (self.w - 1 - i))

        self.bitfield = np.zeros(total_bits, dtype=np.uint8)
        self.step = 0

    def get_layer_data(self):
        s_g  = run_graviton_filter(self.bitfield, self.w, self.target_val)
        g_indices  = np.where(s_g == 1)[0].astype(np.float64)

        s_l1 = run_recursive_density_filter(s_g,  self.l1_w, self.l1_t)
        l1_indices = np.where(s_l1 == 1)[0].astype(np.float64)

        s_l2 = run_recursive_density_filter(s_l1, self.l2_w, self.l2_t)
        l2_indices = np.where(s_l2 == 1)[0].astype(np.float64)

        s_l3 = run_recursive_density_filter(s_l2, self.l3_w, self.l3_t)
        l3_indices = np.where(s_l3 == 1)[0].astype(np.float64)

        if g_indices.size > 0:
            l0_r = g_indices
            l1_r = l1_indices * self.l1_w
            l2_r = l2_indices * (self.l1_w * self.l2_w)
            l3_r = l3_indices * (self.l1_w * self.l2_w * self.l3_w)
        else:
            l0_r = l1_r = l2_r = l3_r = np.zeros(0)

        return l0_r, l1_r, l2_r, l3_r

    def mutate_state(self, mutations_per_step: int):
        for _ in range(mutations_per_step):
            idx = random.randint(0, self.total_bits - 1)
            self.bitfield[idx] ^= 1
        self.step += 1


def compute_hubble(history_steps, history_active):
    if len(history_active) < 2: return np.array([]), np.array([])
    steps = np.array(history_steps, dtype=float)
    act   = np.array(history_active, dtype=float)
    dact, dsteps = np.diff(act), np.diff(steps)
    valid = (np.abs(dsteps) > 1e-12) & (act[:-1] > 1.0)
    H = np.zeros(len(dact))
    H[valid] = (dact[valid] / dsteps[valid]) / act[:-1][valid]
    return steps[:-1], H


def generate_even_coordinates(count, scale):
    if count <= 0:  return np.zeros(0)
    if count == 1:  return np.array([0.0])
    return np.linspace(-0.5, 0.5, count) * scale


# ===========================================================================
# MAIN PROGRAM EXECUTION
# ===========================================================================

if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="Hybrid Entropic Cosmology Engine.")
    
    parser.add_argument("--bits", type=int, default=65535)
    parser.add_argument("--pattern", type=str, default="01")
    parser.add_argument("--quantum_mutations", type=int, default=100)
    parser.add_argument("--max_time_steps", type=int, default=1000)
    parser.add_argument("--feynman", action="store_true")
    parser.add_argument("--spectrum", type=str, default=None, 
                        help="Path to JSON dataset. Activates Hybrid Guided Mode alongside the bitfield engine.")
    parser.add_argument("--age", type=float, default=13.8e9)
    parser.add_argument("--time_scale_mode", type=str, default="log", choices=["log", "linear"])
    parser.add_argument("--hubble_sensitivity", type=float, default=0.1)

    parser.add_argument("--l1_window", type=int, default=8)
    parser.add_argument("--l1_threshold", type=int, default=5)
    parser.add_argument("--l2_window", type=int, default=6)
    parser.add_argument("--l2_threshold", type=int, default=3)
    parser.add_argument("--l3_window", type=int, default=8)
    parser.add_argument("--l3_threshold", type=int, default=3)
    args = parser.parse_args()

    engine = EntropicCosmologyEngine(
        args.bits, args.pattern,
        args.l1_window, args.l1_threshold, args.l2_window, args.l2_threshold,
        args.l3_window, args.l3_threshold
    )

    n_max = max(1.0, float(args.bits // engine.w))
    mapper = HybridSpectrumMapper(args.spectrum, args.age) if args.spectrum else None

    # Track histories
    history_timestamps = []
    history_entropy_track = []
    history_g_counts = []
    history_l1_counts = []
    history_l2_counts = []
    history_l3_counts = []
    history_active = []
    history_h_predicted = []

    plt.ion()
    fig, (ax_spacetime, ax_metrics) = plt.subplots(1, 2, figsize=(16, 7))
    fig.suptitle(f"IAME Cosmology Engine [HYBRID CORE MODE]", fontsize=16, fontweight='bold')

    ax_spacetime.set_facecolor('#020205')
    ax_spacetime.set_xlabel("Cosmic Time")
    ax_spacetime.set_ylabel("Relational Spatial Coordinate")
    ax_metrics.set_ylabel("Structural Count")
    ax_metrics.set_xlabel("Cosmic Time")

    if mapper:
        ax_spacetime.set_xscale('log')
        ax_metrics.set_xscale('log')
        ax_spacetime.set_xlim(mapper.T_MIN_YEARS, mapper.t_max_years)
        ax_metrics.set_xlim(mapper.T_MIN_YEARS, mapper.t_max_years)
    else:
        ax_spacetime.set_xlim(0, args.max_time_steps)
        ax_metrics.set_xlim(0, args.max_time_steps)

    l0_scatter = ax_spacetime.scatter([], [], s=1, color='gray', alpha=0.10, label="L0 Fabric")
    l1_scatter = ax_spacetime.scatter([], [], s=1, color='cyan', alpha=0.30, label="L1 Neutrinos")
    l2_scatter = ax_spacetime.scatter([], [], s=2, color='magenta', alpha=0.50, label="L2 Hadrons")
    l3_scatter = ax_spacetime.scatter([], [], s=4, color='lime', alpha=0.70, label="L3 Atoms")
    
    all_time_l0_t, all_time_l0_r = [], []
    all_time_l1_t, all_time_l1_r = [], []
    all_time_l2_t, all_time_l2_r = [], []
    all_time_l3_t, all_time_l3_r = [], []

    line_g,       = ax_metrics.plot([], [], label="L0 Free Fabric", color='gray', lw=1, linestyle=':')
    line_l1,      = ax_metrics.plot([], [], label="L1 Neutrinos",   color='cyan',    lw=2)
    line_l2,      = ax_metrics.plot([], [], label="L2 Hadrons",     color='magenta', lw=2)
    line_l3,      = ax_metrics.plot([], [], label="L3 Atoms",       color='lime',    lw=2.5)
    
    ax_entropy = ax_metrics.twinx()
    line_entropy, = ax_entropy.plot([], [], label="Shannon Entropy", color='red', linestyle='--', lw=1.5)
    line_hubble,  = ax_entropy.plot([], [], label="H(t) True", color='yellow', linestyle='-', lw=1.5)
    line_h_pred,  = ax_entropy.plot([], [], label="H(t) Observed", color='orange', linestyle='-.', lw=2)
    ax_entropy.set_ylim(-0.05, 1.2)

    current_time_tick = 0

    # -----------------------------------------------------------------------
    # DUAL-TRACK SIMULATION LOOP
    # -----------------------------------------------------------------------
    while current_time_tick < args.max_time_steps:
        if not plt.fignum_exists(fig.number): break

        current_time_tick += 1
        
        # ALWAYS RUN BIT ENGINE MUTATION (The Universal Fabric Clock)
        engine.mutate_state(args.quantum_mutations)
        l0_pos_raw, l1_pos_raw, l2_pos_raw, l3_pos_raw = engine.get_layer_data()
        raw_l0_fabric = l0_pos_raw.size

        if mapper:
            # Synchronize bit ticks to cosmic historical years
            if args.time_scale_mode == "log":
                log_min, log_max = np.log10(mapper.T_MIN_YEARS), np.log10(mapper.t_max_years)
                loop_fraction = current_time_tick / args.max_time_steps
                current_real_time = 10 ** (log_min + loop_fraction * (log_max - log_min))
                step_fraction = loop_fraction
            else:
                loop_fraction = current_time_tick / args.max_time_steps
                current_real_time = mapper.T_MIN_YEARS + loop_fraction * (mapper.t_max_years - mapper.T_MIN_YEARS)
                step_fraction = np.clip((np.log10(current_real_time) - np.log10(mapper.T_MIN_YEARS)) / (np.log10(mapper.t_max_years) - np.log10(mapper.T_MIN_YEARS)), 0.0, 1.0)
            
            # TRACK B: Sample Guided Empirical Data Fractions
            emp_fractions = mapper.get_empirical_fractions(step_fraction)
            
            # Distribute the actual active bit budget based on real-world curves
            net_l3 = int(emp_fractions.get("L3", 0) * (n_max * 0.25))
            net_l2 = int(emp_fractions.get("L2", 0) * (n_max * 0.25))
            net_l1 = int(emp_fractions.get("L1", 0) * (n_max * 0.25))
            
            # The remaining unbound bits contract or expand relational metric space
            net_l0 = max(1, int(raw_l0_fabric - (net_l1 + net_l2 + net_l3)))
            sim_indicator = compute_entropy(engine.bitfield)
        else:
            # TRACK A: Standard Algorithmic Filters only
            current_real_time = float(current_time_tick)
            net_l3 = l3_pos_raw.size
            net_l2 = max(0, l2_pos_raw.size - (net_l3 * int(args.l3_window)))
            net_l1 = max(0, l1_pos_raw.size - (l2_pos_raw.size * int(args.l2_window)))
            net_l0 = max(0, raw_l0_fabric - (l1_pos_raw.size * int(args.l1_window)))
            sim_indicator = compute_entropy(engine.bitfield)

        # Relational coordinate calculations
        active_elements = max(1, net_l0)
        total_scale     = (active_elements / n_max) * 4.0

        history_active.append(active_elements)
        history_timestamps.append(current_real_time)
        history_entropy_track.append(sim_indicator)
        history_g_counts.append(net_l0)
        history_l1_counts.append(net_l1)
        history_l2_counts.append(net_l2)
        history_l3_counts.append(net_l3)

        _, H_vals = compute_hubble(history_timestamps, history_active)
        
        total_bound_matter = net_l1 + net_l2 + net_l3
        resolution_bias = total_bound_matter / (net_l0 + 1.0)
        latest_H_true = H_vals[-1] if len(H_vals) > 0 else 0.0
        latest_H_predicted = latest_H_true * (1.0 + args.hubble_sensitivity * resolution_bias)
        history_h_predicted.append(latest_H_predicted)

        # Append visualization coordinates
        def _append(t, count, t_list, r_list):
            norm = np.linspace(-0.5, 0.5, count) if count > 0 else np.zeros(0)
            for v in norm:
                t_list.append(t)
                r_list.append(v * total_scale)

        _append(current_real_time, net_l0, all_time_l0_t, all_time_l0_r)
        _append(current_real_time, net_l1, all_time_l1_t, all_time_l1_r)
        _append(current_real_time, net_l2, all_time_l2_t, all_time_l2_r)
        _append(current_real_time, net_l3, all_time_l3_t, all_time_l3_r)

        if all_time_l0_t: l0_scatter.set_offsets(np.column_stack((all_time_l0_t, all_time_l0_r)))
        if all_time_l1_t: l1_scatter.set_offsets(np.column_stack((all_time_l1_t, all_time_l1_r)))
        if all_time_l2_t: l2_scatter.set_offsets(np.column_stack((all_time_l2_t, all_time_l2_r)))
        if all_time_l3_t: l3_scatter.set_offsets(np.column_stack((all_time_l3_t, all_time_l3_r)))

        ax_spacetime.set_ylim(-max(0.05, total_scale * 0.55), max(0.05, total_scale * 0.55))

        line_g.set_data(history_timestamps,  history_g_counts)
        line_l1.set_data(history_timestamps, history_l1_counts)
        line_l2.set_data(history_timestamps, history_l2_counts)
        line_l3.set_data(history_timestamps, history_l3_counts)
        line_entropy.set_data(history_timestamps, history_entropy_track)

        if len(H_vals) > 1:
            max_h_scale = np.max(np.abs(H_vals)) + 1e-12
            line_hubble.set_data(history_timestamps[:-1], H_vals / max_h_scale * 0.5)
            line_h_pred.set_data(history_timestamps[:-1], np.array(history_h_predicted[:-1]) / max_h_scale * 0.5)

        ax_metrics.relim()
        ax_metrics.autoscale(enable=True, axis='y', tight=False)
        ax_entropy.relim()

        fig.canvas.draw_idle()
        plt.pause(0.002)

    plt.ioff()
    plt.show()
